apiVersion: v1
kind: Service
metadata:
  name: service-t-infra-zookeeper
spec:
  type: NodePort
  selector:
    app: t-infra-zookeeper
  ports:
    - port: 2181
      nodePort: 30181
      targetPort: 2181