kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-t-infra-pgadmin
  namespace: t-project
  labels:
    app: t-infra-pgadmin
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi