kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-t-infra-redis-0
  labels:
    type: local
    app: t-infra-redis-0
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    type: DirectoryOrCreate
    path: /run/desktop/mnt/host/c/Volumes/t-infra-redis-0