apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-t-infra-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t-infra-kafka
  template: 
    metadata:
      name: pod-t-infra-kafka
      labels:
        app: t-infra-kafka
    spec:
      containers:
        - name: container-t-infra-kafka
          image: wurstmeister/kafka:2.13-2.8.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: service-t-infra-zookeeper:2181
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://service-t-infra-kafka:9092"